### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by nluetts** [jbytecode/ErrorsInVariables.jl#1]
Hi :wave:

I read through the readme and had some trouble understanding the example.
I suppose 

```
dirtyx = cleanx
``` 

in your code example is supposed to read

```
dirtyx = cleanx + deltax
```

?

**Comment by jbytecode** [comment]
Thank you for your interest. Would you like to send a pull request?

**Comment by nluetts** [comment]
That seems to be a little bit too small a contribution for a PR :slightly_smiling_face: 
Just wanted to point it out so others would not trip over it.

**Comment by jbytecode** [comment]
Solved. Thank you!
